### ISSUE TITLE
mapim does not support optional argument extend

### ISSUE THREAD

**Issue by crawld** [indus/kubi#15]
after updating to 0.1.6, i get:

```
  File ".local/lib/python3.10/site-packages/kubi/kubi.py", line 226, in kubi
    mapim = img.mapim(idx, interpolate=interp, extend="repeat")
  File ".local/lib/python3.10/site-packages/pyvips/vimage.py", line 1354, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File ".local/lib/python3.10/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: mapim does not support optional argument extend
```

what version of pyvips adds supports for extend argument? i'm using pyvips==2.2.3

**Comment by indus** [comment]
I think you need to Update libvips to v8.13 or higher. Pyvips seems to be the latest version, right?Am 17.09.2024 22:22 schrieb crawld ***@***.***>:
after updating to 0.1.6, i get:
  File ".local/lib/python3.10/site-packages/kubi/kubi.py", line 226, in kubi
    mapim = img.mapim(idx, interpolate=interp, extend="repeat")
  File ".local/lib/python3.10/site-packages/pyvips/vimage.py", line 1354, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File ".local/lib/python3.10/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: mapim does not support optional argument extend

what version of pyvips adds supports for extend argument? i'm using pyvips==2.2.3

**Comment by crawld** [comment]
thanks. i am using libvips 8.12.1 that is the default on ubuntu 22.04.

**Comment by indus** [comment]
Hm - maybe you just want to stick to kubi version 0.1.5.The usage of the extend option is the only difference. Here is the issue that made it necessary: https://github.com/indus/kubi/issues/3If you don't face the black seam problem in your setup an update is not needed.Am 17.09.2024 22:44 schrieb crawld ***@***.***>:
thanks. i am using libvips 8.12.1 that is the default on ubuntu 22.04.

**Comment by crawld** [comment]
i'll stick with 0.1.5. i don't have any black seams. thanks!
