### ISSUE TITLE
Facing problem to run Kubi in shell script

### ISSUE THREAD

**Issue by wuuuaaaa** [indus/kubi#5]
Hi, 

I have installed Kubi with python 3.6 and libvips by following this guide (https://tufora.com/tutorials/linux/general/install-vips-vips-tools-and-vips-devel-libvips-on-centos-7)

If i run kubi command in terminal, it is working fine.
However, when i run it in shell script it is having problem to load libvips.so.42
Is it some path setup missing in my shell script? Hope you can enlighten me on this.
Thanks.

```
Error Output: ================ 
Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/pyvips/__init__.py", line 19, 
in import _libvips ModuleNotFoundError: No module named '_libvips' During handling of the above exception, 
another exception occurred: Traceback (most recent call last): File "/usr/local/bin/kubi", 
line 33, in sys.exit(load_entry_point('kubi==0.1.4', 'console_scripts', 'kubi')()) File "/usr/local/lib/python3.6/site-packages/kubi/kubi.py", 
line 335, in run main(sys.argv[1:]) File "/usr/local/lib/python3.6/site-packages/kubi/kubi.py", 
line 331, in main kubi(args) File "/usr/local/lib/python3.6/site-packages/kubi/kubi.py", 
line 38, in kubi import pyvips File "/usr/local/lib/python3.6/site-packages/pyvips/__init__.py", 
line 71, in vips_lib = ffi.dlopen(_vips_libname) File "/usr/local/lib64/python3.6/site-packages/cffi/api.py", 
line 150, in dlopen lib, function_cache = _make_ffi_library(self, name, flags) File "/usr/local/lib64/python3.6/site-packages/cffi/api.py", 
line 832, in _make_ffi_library backendlib = _load_backend_lib(backend, libname, flags) File "/usr/local/lib64/python3.6/site-packages/cffi/api.py",
line 827, in _load_backend_lib raise OSError(msg) OSError: cannot load library 'libvips.so.42': /lib64/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates. Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42' 
```

**Comment by indus** [comment]
I'm working mostly in Windows. So I'm probably not a good help for your questions.

It looks like this is a libvips problem that showed up before:
https://github.com/libvips/libvips/issues/1814
https://github.com/libvips/ruby-vips/issues/219

Could you check there if there is some hint that fixes the problem?

**Comment by wuuuaaaa** [comment]
Sigh... nothing work out yet. 
i created a discussion on libvips on this matter got closed by maintainer @@ i feel hopeless now 

btw is there anyway that i can set parameter in kubi/python to let it load the lib path?

thanks.

**Comment by indus** [comment]
@wuuuaaaa looks like this is still making progress upstream: https://github.com/libvips/pyvips/issues/356#issuecomment-1288883675

But you can also try to do something similar like https://github.com/indus/kubi/blob/main/src/kubi/kubi.py#L34-L36
kubi is just ~350 lines of code in a single file. It should be easy to modify it to your need.

**Comment by indus** [comment]
Does [this fix](https://github.com/libvips/pyvips/issues/356#issuecomment-1293737459) help with your problem? If so feel free to close this.
